# Before using this with conda env, you will need to define the
# environment variable USE_OMP as 'export USE_OMP=0' to get pykdtree
# to install on OSX 10.13.x (and other versions of OSX?). Also 
# note that while conda will try to install cartopy, I could not
# get it to install the lastest version (0.18.0, 5/7/20) but I 
# get pip to install it.

name: opendap
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy
  - h5py
  - scipy
  - ipykernel
  - pip:
    - maptplotlib
    - cartopy
    - pykdtree